routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    if (session()->has('userLogged')) {
        if (session()->get('userLogged') != null) {
            return redirect()->route('dashboard');
}
return redirect()->route('login');
}
return redirect()->route('login');
});
Auth::routes();
Route::get('/not-found', 'HomeController@not_found')->name('notFound');
Route::group(['middleware' => 'isHaveToken'], function()
{
Route::get('/rekap-presensi', 'RekapPresensiController@index');
Route::get('/get-siswa/{jadwal}', 'JadwalController@get_siswa');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::resource('users', 'UserController');
Route::resource('guru', 'GuruController');
Route::resource('kelas', 'KelasController');
Route::resource('siswa', 'SiswaController');
Route::resource('mapel', 'MapelController');
Route::resource('jadwal', 'JadwalController');
Route::resource('presensi', 'PresensiController');
Route::get('/account', 'AccountController@account')->name('account.index');
Route::post('/account', 'AccountController@account_save')->name('account.store');
});

app/Http/Controllers/JadwalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;

class JadwalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {               
        $response = Http::withToken(session()->get('tokenUser'))
                            ->get(env("REST_API_ENDPOINT").'/api/jadwal');
        $dataResponse = json_decode($response);
        $this->data['jadwals'] = $dataResponse->data;

        return view('jadwal.index',$this->data); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $responseKelas = Http::withToken(session()->get('tokenUser'))
                                ->get(env("REST_API_ENDPOINT").'/api/kelas');

        $responseMapel = Http::withToken(session()->get('tokenUser'))
                                ->get(env("REST_API_ENDPOINT").'/api/mapel');

        $responseGuru = Http::withToken(session()->get('tokenUser'))
                                ->get(env("REST_API_ENDPOINT").'/api/guru');
        $dataKelas = json_decode($responseKelas);
        $dataMapel = json_decode($responseMapel);
        $dataGuru = json_decode($responseGuru);

        $this->data['dataKelas'] = $dataKelas->data;
        $this->data['dataGuru'] = $dataGuru->data;
        $this->data['dataMapel'] = $dataMapel->data;

        return view('jadwal.create',$this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $response = Http::withToken(session('tokenUser'))
                            ->post(
                                env("REST_API_ENDPOINT").'/api/jadwal',
                                $request->except('_token')
                            );
        $data = json_decode($response);

        if ($data->status == true) {
            return redirect()->route('jadwal.index')->with('success','Data jadwal berhasil ditambahkan!');
        } else {
            return redirect()->route('jadwal.create')->with('validationErrors',$data->message);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $response = Http::withToken(session()->get('tokenUser'))
                            ->get(env("REST_API_ENDPOINT").'/api/jadwal/'.$id);
        $dataResponse = json_decode($response);
        
        $responseKelasDepedencies = Http::withToken(session()->get('tokenUser'))
                                            ->get(env("REST_API_ENDPOINT").'/api/kelas');
        $responseMapelDepedencies = Http::withToken(session()->get('tokenUser'))
                                            ->get(env("REST_API_ENDPOINT").'/api/mapel');
        $responseGuruDepedencies = Http::withToken(session()->get('tokenUser'))
                                            ->get(env("REST_API_ENDPOINT").'/api/guru');

        $dataDepedenciesKelas = json_decode($responseKelasDepedencies);
        $dataDepedenciesMapel = json_decode($responseMapelDepedencies);
        $dataDepedenciesGuru = json_decode($responseGuruDepedencies);

        if ($dataResponse->status == true) {
            $jadwal = $dataResponse->data;
            $kelas = $dataDepedenciesKelas->data;
            $mapel = $dataDepedenciesMapel->data;
            $guru = $dataDepedenciesGuru->data;

            $this->data['jadwal'] = $jadwal;
            $this->data['dataKelas'] = $dataDepedenciesKelas->data;
            $this->data['mapels'] = $dataDepedenciesMapel->data;
            $this->data['dataGuru'] = $dataDepedenciesGuru->data;

            return view('jadwal.edit',$this->data);
        } else {
            return redirect()->route('jadwal.index')->with('danger','Data jadwal tidak dapat ditemukan!');
        } 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $response = Http::withTOken(session('tokenUser'))
                            ->put(
                                env("REST_API_ENDPOINT").'/api/jadwal/'.$id,
                                $request->except(['_token','_method'])
                            );
        $data = json_decode($response);

        if ($data->status == true) {
            return redirect()->route('jadwal.index')->with('success','Data jadwal berhasil diubah!');
        } else {
            return redirect()->route('jadwal.edit',$id)->with('validationErrors',$data->message);
        } 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $response = Http::withTOken(session('tokenUser'))
                            ->delete(
                                env("REST_API_ENDPOINT").'/api/jadwal/'.$id);
        $data = json_decode($response);

        if ($data->status == true) {
            return redirect()->route('jadwal.index')->with('success','Data jadwal berhasil dihapus!');
        } else {
            return redirect()->route('jadwal.index')->with('validationErrors',$data->message);
        } 
    }

    public function get_siswa($jadwal)
    {
        $response = Http::withToken(session()->get('tokenUser'))->get(env("REST_API_ENDPOINT").'/api/get-siswa/'.$jadwal);
        $data = json_decode($response);

        return view('presensi.index',[
            'presensi' => $data
        ]); 
    }
}

resources/views/jadwal/create.blade.php
@extends('layouts/main-admin')

@section('title', 'Tambah Jadwal')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">JADWAL</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Tambah Jadwal</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('jadwal.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">                    
                    <div class="form-group">
                        <label for="exampleInputJK">Kelas</label>
                        <select class="form-control" name="kelas_id" id="kelas_id" required>
                            @foreach ($dataKelas as $key => $kelas)
                                <option value="{{ $kelas->id }}">{{ $kelas->nama_kelas }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Mata Pelajaran</label>
                        <select class="form-control" name="mapel_id" id="mapel_id" required>
                            @foreach ($dataMapel as $key => $mapel)
                                <option value="{{ $mapel->id }}">{{ $mapel->nama_mapel }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Guru Pengampu</label>
                        <select class="form-control" name="guru_id" id="guru_id" required>
                            @foreach ($dataGuru as $key => $guru)
                                <option value="{{ $guru->id }}">{{ $guru->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Hari</label>
                        <select class="form-control" name="hari" id="hari" required>
                            <option value="">Pilih Hari</option>
                            <option value="senin">Senin</option>
                            <option value="selasa">Selasa</option>
                            <option value="rabu">Rabu</option>
                            <option value="kamis">Kamis</option>
                            <option value="jumat">Jumat</option>
                            <option value="sabtu">Sabtu</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Jam Pelajaran</label>
                        <input type="text" class="form-control" name="jam_pelajaran" id="jam_pelajaran" placeholder="ex: 07.00 - 08.40 WIB" required>
                    </div>                                        
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.scripts')
@endsection

resources/views/jadwal/edit.blade.php
@extends('layouts/main-admin')

@section('title', 'Edit Jadwal')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">JADWAL</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Edit Jadwal</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <form role="form" method="post" action="{{ route('jadwal.update',$jadwal->id) }}" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="card-body">                    
                    <div class="form-group">
                        <label for="exampleInputJK">Kelas</label>
                        <select class="form-control" name="kelas_id" id="kelas_id" required>
                            @foreach ($dataKelas as $kelas)
                                <option value="{{ $kelas->id }}" @if ($kelas->id == $jadwal->kelas_id)
                                    selected=""
                                @endif>{{ $kelas->nama_kelas }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Mata Pelajaran</label>
                        <select class="form-control" name="mapel_id" id="mapel_id" required>
                            @foreach ($mapels as $mapel)
                                <option value="{{ $mapel->id }}" @if ($mapel->id == $jadwal->mapel_id)
                                    selected=""
                                @endif>{{ $mapel->nama_mapel }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Guru Pengampu</label>
                        <select class="form-control" name="guru_id" id="guru_id" required>
                            @foreach ($dataGuru as $guru)
                                <option value="{{ $guru->id }}" @if ($guru->id == $jadwal->guru_id)
                                    selected=""
                                @endif>{{ $guru->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJK">Hari</label>
                        <select class="form-control" name="hari" id="hari" required>
                            <option value="senin" @if ($jadwal->hari == 'senin')
                                selected=""
                            @endif>Senin</option>
                            <option value="selasa" @if ($jadwal->hari == 'selasa')
                                selected=""
                            @endif>Selasa</option>
                            <option value="rabu" @if ($jadwal->hari == 'rabu')
                                selected=""
                            @endif>Rabu</option>
                            <option value="kamis" @if ($jadwal->hari == 'kamis')
                                selected=""
                            @endif>Kamis</option>
                            <option value="jumat" @if ($jadwal->hari == 'jumat')
                                selected=""
                            @endif>Jumat</option>
                            <option value="sabtu" @if ($jadwal->hari == 'sabtu')
                                selected=""
                            @endif>Sabtu</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Jam Pelajaran</label>
                        <input type="text" class="form-control" name="jam_pelajaran" id="jam_pelajaran" value="{{ $jadwal->jam_pelajaran }}" required>
                    </div>                                                         
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@include ('includes.scripts')
@endsection

resources/views/jadwal/index.blade.php
@extends('layouts/main-admin')

@section('title', 'Jadwal')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">JADWAL</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Jadwal</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                    <tr>
                    <th width="40">NO</th>
                    <th>KELAS</th>
                    <th>MAPEL</th>
                    <th>GURU PENGAMPU</th>
                    <th>HARI</th>
                    <th>AKSI</th>
                    </tr>
                </thead>
                <tbody>
                    @if (count($jadwals))
                        @foreach ($jadwals as $key => $jadwal)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td>{{ $jadwal->nama_kelas }}</td>
                                <td>{{ $jadwal->nama_mapel }}</td>
                                <td>{{ $jadwal->nama }}</td>
                                <td>{{ $jadwal->hari }}</td>
                                <td class="text-center">
                                    @if(session()->get('userLogged')->type=='admin')
                                    <a href="{{ route('jadwal.edit', $jadwal->id) }}">
                                        <button class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    </a>
                                    <form id="delete-jadwal-{{$jadwal->id}}" action="/jadwal/{{$jadwal->id}}" method="post"
                                        style="display: inline;">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Hapus">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                    @endif
                                    @if(session()->get('userLogged')->type=='guru')
                                    <a href="/get-siswa/{{ $jadwal->id }}">
                                        <button class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Presensi">
                                            <i class="fa fa-fingerprint"></i>
                                        </button>
                                    </a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    @endif
                </tbody>
            </table>
        </div>
    </div>
</section>
@include ('includes.scripts')
@if(session()->get('userLogged')->type=='admin')
    <script type="text/javascript">
        $(document).ready(function(){
            $("#data-admin_length").append('<a  href="{{ route('jadwal.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
        });
    </script>
    @endif
@endsection

resources/views/jadwal/show.blade.php
@extends('layouts/main-admin')

@section('title', 'Data Presensi')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2 class="m-0 text-dark">DATA PRESENSI</h2>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item active">Data Presensi</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="container-fluid">
    <div class="card">
        @include ('includes.flash')
        <div class="card-body">
            <div class="card-body">
                <table class="table">
                                        
                    <tr>
                        <td>KELAS</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>GURU PENGAMPU</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>MATA PELAJARAN</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>HARI</td>
                        <td>: </td>
                    </tr>
                    <tr>
                        <td>JAM PELAJARAN</td>
                        <td>: </td>
                    </tr>                                                           
                </table>   
                <hr>
                <h4>Data Siswa</h4>     
                <table class="table">
                    <thead>
                        <tr>
                            <th>NO</th>
                            <th>NAMA</th>
                            <th>STATUS</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{-- looping data siswa --}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
@include ('includes.scripts')
@endsection